/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddScheduleCalendar: typeof import('./../components/addScheduleCalendar.vue')['default']
    CalendarItem: typeof import('./../components/CalendarItem.vue')['default']
    LayoutHeader: typeof import('./../components/layout-header.vue')['default']
    MonthCalendar: typeof import('./../components/MonthCalendar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleCalendarHeader: typeof import('./../components/ScheduleCalendarHeader.vue')['default']
    ScheduleHeader: typeof import('./../components/ScheduleHeader.vue')['default']
    UserLogin: typeof import('./../components/UserLogin.vue')['default']
    UserLogout: typeof import('./../components/UserLogout.vue')['default']
  }
}
