/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CalendarItem: typeof import('./../components/CalendarItem.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    MonthCalendar: typeof import('./../components/MonthCalendar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
