/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./../components/common/AboutMe.vue')['default']
    AddScheduleCalendar: typeof import('./../components/intend/addScheduleCalendar.vue')['default']
    CalendarItem: typeof import('./../components/intend/CalendarItem.vue')['default']
    Confetti: typeof import('./../components/intend/Confetti.vue')['default']
    EditScheduleCalendar: typeof import('./../components/intend/editScheduleCalendar.vue')['default']
    MonthCalendar: typeof import('./../components/intend/MonthCalendar.vue')['default']
    MoreSetting: typeof import('./../components/common/MoreSetting.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduleCalendarHeader: typeof import('./../components/intend/ScheduleCalendarHeader.vue')['default']
    StatusIcon: typeof import('./../components/common/StatusIcon.vue')['default']
    UserLogin: typeof import('./../components/common/UserLogin.vue')['default']
  }
}
